---
- name: Pull and Run docker image of hritik97/addjency_backend
  hosts: all
  tasks:
    - name: Pull addjency_backend
      docker_image:
        name: addjency_backend
        source: pull

    - name: Pull MySQl image
      docker_image:
        name: mysql:5.7
